#!/bin/sh

LINUX_VERSION=linux-5.10
COMPLIE_TOOLS=aarch64-linux-gnu-

usage()
{
	if [  -n $1 ];then
		echo "板卡arm64 menuconfig 配置 sh build_arm64 -m (imx6dl | vexpress)"
		echo "板卡arm64 zImage 编译 sh build_arm64 -k (imx6dl | vexpress)"
	fi
}

#vexpress
make_vexpress_menuconfig()
{
	cd $LINUX_VERSION
	cp arch/arm/configs/defconfig ./.config
	make ARCH=arm menuconfig
	if [ -f .config ];then
		mv .config arch/arm64/configs/defconfig
	fi
	cd -
}
make_vexpress_zImage()
{
	cd $LINUX_VERSION
	export KBUILD_OUTPUT=../out/out_vexpress_arm64_target
	make ARCH=arm64 defconfig
	make ARCH=arm64 CROSS_COMPILE=${COMPLIE_TOOLS} all -j16
	cd ../
}

#imx6dl
make_imx6dl_menuconfig()
{
	cd $LINUX_VERSION
	cp arch/arm/configs/imx_v6_v7_defconfig ./.config
	make ARCH=arm menuconfig
	if [ -f .config ];then
		mv .config arch/arm64/configs/imx_v6_v7_defconfig
	fi
	cd -
}
make_imx6dl_zImage()
{
	cd $LINUX_VERSION
	export KBUILD_OUTPUT=../out/out_imx6dl_arm64_target
	make ARCH=arm64 imx_v6_v7_defconfig
	make ARCH=arm64 CROSS_COMPILE=${COMPLIE_TOOLS} all -j16
	cd ../
}

build_linux_kernel()
{
	case $1 in
		imx6dl)
			# 没调试
			# make_imx6dl_zImage
			;;
		vexpress)
			make_vexpress_zImage
			;;
	esac
}
build_linux_menuconfig()
{
	case $1 in
		imx6dl)
			# 没调试
			# make_imx6dl_menuconfig	
			;;
		vexpress)
			make_vexpress_menuconfig
			;;
	esac
}
	
if [  $# -eq 0 ];then
	usage;
	exit 1;
fi

while getopts "k:m:h" opt;
do
	case $opt in
		k)
			build_linux_kernel $OPTARG
			;;
		m)
		build_linux_menuconfig $OPTARG
			;;
		h)
			usage
			;;
	esac
done 

