#!/bin/sh

LINUX_VERSION=linux-5.10

make_vexpress()
{
	cd $LINUX_VERSION
	export KBUILD_OUTPUT=../out_vexpress_arm32_target
	make ARCH=arm vexpress_defconfig
	make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- all -j16
	cd ../
}
make_imx6dl()
{
	cd $LINUX_VERSION
	export KBUILD_OUTPUT=../out_imx6dl_arm32_target
	make ARCH=arm imx_v6_v7_defconfig
	make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- all -j16
	cd ../
}

if [  -n $1 ];then
	echo "sh run_arm32.sh (vexpress | imx6dl )"
fi
case $1 in
	imx6dl)
		make_imx6dl
		;;
	vexpress)
		make_vexpress
		;;
esac
