#!/bin/bash


export ARCH=arm
export CROSS_COMPILE=arm-linux-gnueabihf-
CROSS_COMPILE_DIR=/opt/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf
INSTALL_DIR=/home/arctan/workspace/linux/rootfs/busybox/busybox_rootfs
BUSYBOX_DIR=/home/arctan/workspace/linux/rootfs/busybox/busybox-1.35.0
# BUSYBOX_DIR=/home/arctan/workspace/linux/rootfs/busybox/busybox-1.29.3
OUTPUT_FILE=busybox_rootfs.ext4
cd $BUSYBOX_DIR

make
make install CONFIG_PREFIX=$INSTALL_DIR
if [ $? != 0 ];
then
	echo "Build Busybox Rootfs failed"
	cd -
	exit -1
fi
cd -
cd $INSTALL_DIR
mkdir lib
mkdir usr/lib
mkdir dev proc mnt sys tmp root etc etc/init.d

cd etc/init.d
touch rcS
chmod +x rcS
echo "echo -e && echo \"====== Welcome To Visit ======\" && echo -e" > rcS

cd $CROSS_COMPILE_DIR/arm-linux-gnueabihf/libc/lib
cp *.so *.a $INSTALL_DIR/lib -d
cd $INSTALL_DIR/lib
rm ld-linux-armhf.so.3
cd $CROSS_COMPILE_DIR/arm-linux-gnueabihf/libc/lib
cp ld-linux-armhf.so.3 $INSTALL_DIR/lib

cd $INSTALL_DIR/lib
ln -s libm-2.25.so libm.so.6
ln -s libresolv-2.25.so libresolv.so.2
ln -s libc-2.25.so libc.so.6
cd $INSTALL_DIR/dev
sudo mknod -m 666 tty1 c 4 1
sudo mknod -m 666 tty2 c 4 2
sudo mknod -m 666 tty3 c 4 3
sudo mknod -m 666 tty4 c 4 4
sudo mknod -m 666 console c 5 1
sudo mknod -m 666 null c 1 3



cd $CROSS_COMPILE_DIR/arm-linux-gnueabihf/libc/usr/lib
cp *.so *.a $INSTALL_DIR/usr/lib/ -d

cd $INSTALL_DIR
# mkdir dev proc mnt sys tmp root

cd $INSTALL_DIR/../
sudo dd if=/dev/zero of=$OUTPUT_FILE seek=0 count=1M bs=400
sudo mkfs.ext4 $OUTPUT_FILE -d $INSTALL_DIR
sudo chmod 777 $OUTPUT_FILE
sudo e2fsck -p -f $OUTPUT_FILE
sudo resize2fs -M $OUTPUT_FILE
qemu-img resize $OUTPUT_FILE 1G

##1、编译busybox 
##修改busybox-1.29.3
##ARCH = arm
##CROSS_COMPILE = arm-linux-gnueabihf-
##
##make 
##make install
##
##2、mkdir busybox_rootfs
##cp /.../busybox-1.29.3/_install/* busybox_rootfs/ -rfd
##mkdir busybox_rootfs/lib
##cp /usr/arm-linux-gnueabi/lib/* busybox_rootfs/lib/ -rfp
#
#
#
##sudo mknod -m 666 busybox_rootfs/dev/tty1 c 4 1
##sudo mknod -m 666 busybox_rootfs/dev/tty2 c 4 2
##sudo mknod -m 666 busybox_rootfs/dev/tty3 c 4 3
##sudo mknod -m 666 busybox_rootfs/dev/tty4 c 4 4
##sudo mknod -m 666 busybox_rootfs/dev/console c 5 1
##sudo mknod -m 666 busybox_rootfs/dev/null c 1 3
#
#dd if=/dev/zero of=busybox_rootfs.ext4 bs=1M count=60
#
#sudo mkfs.ext4 busybox_rootfs.ext4 -d busybox_rootfs
##sudo mkfs.ext3 -F -E nodiscard busybox_rootfs.ext3 -d busybox_rootfs
##sudo mkfs.ext3 busybox_rootfs.ext3
##
##sudo mount -t ext3 busybox_rootfs.ext3 /mnt -o loop
##sudo cp -rf busybox_rootfs/* /mnt/
##sudo umount /mnt
##
#
